In [1]:
import numpy as np
from scipy.sparse import csr_matrix as csr
from scipy.sparse import eye
import random

# LU Decomposition

In [2]:
def LU_decompse(A): # LU разложение Вход 2х мерный массив, Выход 2х мерные массивы
    n_rows = len(A)
    n_cols = len(A[0])
    L = np.eye(n_rows, n_cols)
    U = np.zeros((n_rows, n_cols))
    for i in range(n_rows):
        for j in range(n_cols):
            if i <= j:
                _s = 0
                for k in range(i):
                    _s += L[i][k] * U[k][j]
                U[i][j] = A[i][j] - _s
            else:
                _s = 0
                for k in range(j):
                    _s += L[i][k] * U[k][j]
                L[i][j] = (A[i][j] - _s) / U[j][j]
    return L, U

In [3]:
def LU_decompse_csr(A): # LU разложение Вход csr матрица Выход csr матрица (не оптимально)
    n_rows, n_cols = A.shape
    L = eye(n_rows, n_cols, format="csr")
    U = csr((n_rows, n_cols), dtype=float)
    for i in range(n_rows):
        for j in range(n_cols):
            if i <= j:
                _s = 0
                for k in range(i):
                    _s += L[i, k] * U[k, j]
                U[i, j] = A[i, j] - _s
            else:
                _s = 0
                for k in range(j):
                    _s += L[i, k] * U[k, j]
                L[i, j] = (A[i, j] - _s) / U[j, j]
    return L, U

In [4]:
def LU_decompse_csr_full(A):
    n_rows, n_cols = A.shape
    l_data = []
    l_indices = []
    l_indptr = []
    u_data = []
    u_indices = []
    u_indptr = []
    for i in range(n_rows):
        l_indptr.append(len(l_data))
        u_indptr.append(len(u_data))
        for j in range(n_cols):
            if i <= j:
                _s = 0
                if i == j:
                    l_data.append(1)
                    l_indices.append(j)
                for x, y in zip(l_data[l_indptr[i]:], list(map(lambda x: x[0], filter(lambda x: x[1] == j, zip(u_data, u_indices))))):
                    _s += x * y
                u_data.append(A[i, j] - _s)
                u_indices.append(j)
            else:
                _s = 0
                for x, y in zip(l_data[l_indptr[i]:], list(map(lambda x: x[0], filter(lambda x: x[1] == j, zip(u_data, u_indices))))):
                    _s += x * y
                l_data.append((A[i, j] - _s) / u_data[u_indptr[j]])
                l_indices.append(j)
    l_indptr.append(len(l_data))
    u_indptr.append(len(u_data))
    return csr((l_data, l_indices, l_indptr)), csr((u_data, u_indices, u_indptr))

In [5]:
A = np.array([[10, -7, 0], 
              [-3, 6, 2], 
              [5, -1, 5]])
sA = csr(A)
print("sA")
print(sA)

# print(LU_decompse(A))
# l, u =  LU_decompse_csr(sA)
# print("L: ", l)
# print("U: ", u)

# l, u = LU_decompse_csr_full(sA)
# print("L: ", l.toarray())
# print("U: ", u.toarray())

sA
  (0, 0)	10
  (0, 1)	-7
  (1, 0)	-3
  (1, 1)	6
  (1, 2)	2
  (2, 0)	5
  (2, 1)	-1
  (2, 2)	5


# Usage of sparse matrices

In [6]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
mtx = csr((data, (row, col)), shape=(3, 3))
mtx     

<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 6 stored elements in Compressed Sparse Row format>

In [7]:
mtx.todense()

matrix([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]], dtype=int32)

In [8]:
mtx.data

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [9]:
mtx.indices

array([0, 2, 2, 0, 1, 2], dtype=int32)

In [10]:
mtx.indptr

array([0, 2, 3, 6], dtype=int32)

# Solving a system of linear equations

## Additional functions

In [11]:
# get i-th row of sparse matrix A

def get_row(A, i):
    _, n = A.shape
    row = np.zeros(n)
    non_zero_elements_in_row = A.data[A.indptr[i]:A.indptr[i + 1]]
    indices_of_non_zero_elements_in_row = A.indices[A.indptr[i]:A.indptr[i + 1]]
    k = 0
    for i in range(n):
        if k < len(non_zero_elements_in_row) and i == indices_of_non_zero_elements_in_row[k]:
            row[i] = non_zero_elements_in_row[k]
            k += 1
    return row

## Solve function

In [12]:
# A: sparse matrix
# b: array of values

def solve(A, b):
    L, U = LU_decompse_csr_full(A)
    _, n = A.shape
    
    # solving Ly = b
    y = np.zeros(n)
    for i in range(n):
        row = get_row(L, i)
        y[i] = b[i] - np.dot(y[:i], row[:i])
    
    # solving Ux = y
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        row = get_row(U, i)
        x[i] = (y[i] - np.dot(x[i + 1:], row[i + 1:])) / row[i]
        
    return x

## Example

In [13]:
A = np.array([[10, -7, 2], 
              [-3, 4, 6], 
              [5, -1, 5]])
A_sparse = csr(A)
b = [1, 2, 3]
x = solve(A_sparse, b)
print("Solution: ", x)

Solution:  [0.65168539 0.82022472 0.11235955]


# Finding inverse matrix

In [14]:
def inverse(A):
    _, n = A.shape
    I = np.eye(n)
    A_inverse = np.zeros(A.shape)
    for i in range(n):
        x = solve(A, I[:, i])
        A_inverse[:, i] = x
    return csr(A_inverse)

## Example

In [15]:
A = np.array([[10, -7, 2], 
              [-3, 4, 6], 
              [5, -1, 5]])
A_sparse = csr(A)
A_inverse = inverse(A)
print(A_inverse)

  (0, 0)	-0.2921348314606741
  (0, 1)	-0.3707865168539326
  (0, 2)	0.5617977528089887
  (1, 0)	-0.5056179775280898
  (1, 1)	-0.44943820224719105
  (1, 2)	0.7415730337078651
  (2, 0)	0.19101123595505617
  (2, 1)	0.2808988764044944
  (2, 2)	-0.21348314606741572


# Diagonal Matrices

In [51]:
random.seed()
def generate_diagonal_matrix(k):
    values = [0, -1, -2, -3, -4]
    noise = [1, 10**(-k)]
    matrix = np.zeros((k, k))
    for i in range(k):
        for j in range(k):
            matrix[i][j] = random.choice(values) * random.choice(noise)
        matrix[i][i] = -(sum(matrix[i]) - matrix[i][i])
    return matrix

def solve_d_system(k):
    A = generate_diagonal_matrix(k)
    while abs(np.linalg.det(A)) < 10e-17:
       A = generate_diagonal_matrix(k)
    x = [x for x in range(1, k + 1)]
    F = np.dot(A, x)
    x_new = solve(csr(A), F)
    error = np.linalg.norm(x - x_new)
    return x_new, error

def solve_d_systems(k):
    error_array = []
    x_new_array = []
    for i in range(3, k + 1):
        x_new, error = solve_d_system(i)
        x_new_array.append(x_new)
        error_array.append(error)
        print("k =", i, "\terror =", round(error, 5), "\tx' =", x_new)

solve_d_systems(13)

k = 3 	error = 0.04361 	x' = [1.02517623 2.02517623 3.02517623]
k = 4 	error = 1.42423 	x' = [1.71211586 2.71211586 3.71211586 4.71211586]
k = 5 	error = 5.70445 	x' = [3.55110871 4.55110871 5.55110871 6.55110871 7.55110871]
k = 6 	error = 0.0 	x' = [1. 2. 3. 4. 5. 6.]
k = 7 	error = 13.22876 	x' = [-4.00000000e+00 -3.00000000e+00 -2.00000000e+00 -1.00000000e+00
 -7.01193419e-16  1.00000000e+00  2.00000000e+00]
k = 8 	error = 79.19596 	x' = [29. 30. 31. 32. 33. 34. 35. 36.]
k = 9 	error = 12.6 	x' = [-3.2 -2.2 -1.2 -0.2  0.8  1.8  2.8  3.8  4.8]
k = 10 	error = 0.0 	x' = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
k = 11 	error = 18.79421 	x' = [ 6.66666667  7.66666667  8.66666667  9.66666667 10.66666667 11.66666667
 12.66666667 13.66666667 14.66666667 15.66666667 16.66666667]
k = 12 	error = 8.31384 	x' = [ 3.4  4.4  5.4  6.4  7.4  8.4  9.4 10.4 11.4 12.4 13.4 14.4]
k = 13 	error = 126.19429 	x' = [36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48.]


# Gilbert Matrices

In [24]:
def generate_gilbert_matrix(k):
    matrix = np.zeros((k, k))
    for i in range(k):
        for j in range(k):
            matrix[i][j] = 1 / (i + j + 1)
    return matrix


def solve_system(k):
    A = generate_gilbert_matrix(k)
    x = np.zeros((k))
    for i in range(k):
        x[i] = i + 1
    F = np.dot(A, x)
    x_new = solve(csr(A), F)
    error = np.linalg.norm(x - x_new)
    return x_new, error
    

def solve_systems(k):
    error_array = []
    x_new_array = []
    for i in range(1, k + 1):
        x_new, error = solve_system(i)
        x_new_array.append(x_new)
        error_array.append(error)
        print("k =", i, "\terror =", round(error, 5), "\tx' =", x_new)
#     return error_array, x_new_array
    

solve_systems(13)

k = 1 	error = 0.0 	x' = [1.]
k = 2 	error = 0.0 	x' = [1. 2.]
k = 3 	error = 0.0 	x' = [1. 2. 3.]
k = 4 	error = 0.0 	x' = [1. 2. 3. 4.]
k = 5 	error = 0.0 	x' = [1. 2. 3. 4. 5.]
k = 6 	error = 0.0 	x' = [1. 2. 3. 4. 5. 6.]
k = 7 	error = 0.0 	x' = [1.         2.         2.99999999 4.00000003 4.99999994 6.00000006
 6.99999998]
k = 8 	error = 0.0 	x' = [1.         2.         3.00000005 3.99999975 5.00000066 5.99999909
 7.00000064 7.99999982]
k = 9 	error = 0.00016 	x' = [1.         1.99999989 3.0000018  3.99998727 5.00004631 5.99990609
 7.00010725 7.99993553 9.00001587]
k = 10 	error = 0.00041 	x' = [ 1.          2.00000005  2.99999885  4.00001073  4.99994742  6.0001482
  6.99975132  8.00024521  8.99986893 10.00002929]
k = 11 	error = 0.0345 	x' = [ 0.99999999  2.00000144  2.99996419  4.0003869   4.99776213  6.0076678
  6.98367917  8.0218068   8.98220856 10.00809994 10.99842307]
k = 12 	error = 3.89577 	x' = [ 0.99999976  2.00003     2.99905972  4.01277547  4.9065703   6.40963956
  5.8